# Generated by Django 4.1 on 2025-11-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroTextual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.generotextual')),
            ],
        ),
        migrations.CreateModel(
            name='OcorrenciaConector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('REF', 'Referenciação'), ('SUB', 'Substituição'), ('SEQ', 'Sequenciação')], max_length=3)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.texto')),
            ],
        ),
    ]
